# Generated by Django 5.2.5 on 2025-09-11 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_payment_options_remove_payment_card_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='card_number_mask',
            new_name='card_number_masked',
        ),
    ]
