# Generated by Django 5.2.5 on 2025-08-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='multi_choice_answer',
            field=models.ManyToManyField(blank=True, related_name='multi_answers', to='questionnaire.choise'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'number'), ('choise', 'single choise'), ('multi_choice', 'Multiple Choice')], default='text', max_length=20),
        ),
    ]
