# Generated by Django 5.2.5 on 2025-08-23 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_phoneotp_options_phoneotp_is_used_and_more'),
        ('questionnaire', '0002_answer_multi_choice_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
            ],
            options={
                'verbose_name': 'User Answers',
                'verbose_name_plural': 'Users Answers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
    ]
