# Generated by Django 5.2.5 on 2025-09-11 10:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_alter_question_options_answer_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergoal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usergoal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
